# Generated by Django 5.0 on 2024-10-23 16:40

import account.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(db_column='id', db_comment='id', db_index=True, default=uuid.uuid4, editable=False, help_text='id', primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('email', models.EmailField(db_column='email', db_comment='email', db_index=True, help_text='user email', max_length=200, unique=True, validators=[account.models.validate_email_address], verbose_name='user email')),
                ('username', models.CharField(blank=True, db_index=True, help_text='username', max_length=150, null=True, unique=True, verbose_name='username')),
                ('is_admin', models.BooleanField(db_index=True, default=False, help_text='is user admin', verbose_name='is user admin')),
                ('is_staff', models.BooleanField(db_index=True, default=False, help_text='is user staff', verbose_name='is user staff')),
                ('is_active', models.BooleanField(db_index=True, default=False, help_text='is user active', verbose_name='is user active')),
                ('is_superuser', models.BooleanField(db_index=True, default=False, help_text='is user superuser', verbose_name='is user superuser')),
                ('date_joined', models.DateTimeField(auto_now_add=True, db_index=True, help_text='date joined', verbose_name='date joined')),
                ('user_ip', models.GenericIPAddressField(blank=True, db_index=True, help_text='user ip address', null=True, verbose_name='user ip address')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, help_text='created time', verbose_name='created time')),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, help_text='updated time', verbose_name='updated time')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'user',
                'ordering': ['created'],
            },
        ),
    ]
