# Generated by Django 5.0 on 2024-10-23 17:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, help_text='created time', verbose_name='created time')),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, help_text='updated time', verbose_name='updated time')),
            ],
        ),
        migrations.CreateModel(
            name='FirstSlider',
            fields=[
                ('commonmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.commonmodel')),
                ('image', models.ImageField(db_index=True, help_text='image', upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg', 'jpg'])], verbose_name='image')),
                ('title', models.CharField(blank=True, db_index=True, help_text='enter title', max_length=400, null=True, verbose_name='enter title')),
                ('description', models.TextField(blank=True, db_index=True, help_text='enter description', max_length=400, null=True, verbose_name='enter description')),
                ('is_active', models.BooleanField(blank=True, default=False, help_text='is active', null=True, verbose_name='is active')),
            ],
            bases=('core.commonmodel',),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('commonmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.commonmodel')),
                ('image', models.ImageField(db_index=True, help_text='image', upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg', 'jpg'])], verbose_name='image')),
                ('title', models.CharField(blank=True, db_index=True, help_text='enter title', max_length=400, null=True, verbose_name='enter title')),
                ('description', models.TextField(blank=True, db_index=True, help_text='enter description', max_length=400, null=True, verbose_name='enter description')),
                ('is_active', models.BooleanField(blank=True, default=False, help_text='is active', null=True, verbose_name='is active')),
            ],
            bases=('core.commonmodel',),
        ),
        migrations.CreateModel(
            name='ServiceFeatcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, db_index=True, help_text='enter title', max_length=400, null=True, verbose_name='enter title')),
                ('is_active', models.BooleanField(blank=True, default=False, help_text='is active', null=True, verbose_name='is active')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, help_text='created time', verbose_name='created time')),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, help_text='updated time', verbose_name='updated time')),
                ('service', models.ForeignKey(db_column='service', on_delete=django.db.models.deletion.CASCADE, to='core.service')),
            ],
        ),
    ]
